# Generated by Django 6.0.3 on 2026-03-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_escolhapiloto_piloto_remove_aposta_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piloto',
            name='equipe',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='piloto',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
